name: browser_package_dio
description: Make HTTP requests from inside WASM in Dart using package:dio.
version: 1.0.0
repository: https://github.com/wasm-outbound-http-examples/dart

environment:
  sdk: ^3.5.2

dependencies:
  web: ^1.0.0
  dio: ^5.7.0

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  lints: ^4.0.0
