name: browser_package_fetch_api
description: Make HTTP requests from inside WASM in Dart using package:fetch_api.
version: 1.0.0
repository: https://github.com/wasm-outbound-http-examples/dart

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  fetch_api: ^2.2.0
  web: ^0.5.1

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  lints: ^3.0.0
